name: AI Comment Reply

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  reply:
    runs-on: ubuntu-latest

    # PR Check: Ensure the comment is on a Pull Request, not a regular Issue.
    # FIX APPLIED HERE: Check if the pull_request property exists in the issue object.
    if: github.event.issue.pull_request

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install openai python-dotenv requests

      - name: Run AI Comment Reply
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_USER: ${{ github.event.comment.user.login }}

        run: python ai_comment_reply.py