name: AI Comment Reply

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  reply:
    runs-on: ubuntu-latest

    # 1. PR Check: Ensure the comment is on a Pull Request, not a regular Issue.
    # FIX APPLIED HERE: Check if the pull_request property exists in the issue object.
    if: github.event.issue.pull_request != null

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install openai python-dotenv requests

      # Optional: Add a step to prevent the bot from replying to itself
      - name: Skip if comment is from bot
        id: check_bot_user
        run: |
          # Use the environment variable or literal string for the bot username
          BOT_USERNAME="rparida103"
          COMMENT_USER="${{ github.event.comment.user.login }}"
          if [[ "$COMMENT_USER" == "$BOT_USERNAME" ]]; then
            echo "::notice::Comment made by bot ($BOT_USERNAME). Skipping reply."
            # Use the correct GITHUB_OUTPUT format
            echo "skip_job=true" >> $GITHUB_OUTPUT
          fi

      - name: Run AI Comment Reply
        # Only run if the check_bot_user step didn't set skip_job to true
        if: github.event.issue.pull_request != null && steps.check_bot_user.outputs.skip_job != 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_USER: ${{ github.event.comment.user.login }}

        run: python ai_comment_reply.py